require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'SceneApiAlertTest' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'SceneApiAlertTestTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'SceneApiAlertTest-tvOS' do
  # Pods for SceneApiAlertTest-tvOS

  target 'SceneApiAlertTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
